<a href="https://colab.research.google.com/github/pawan76542987/python/blob/main/pandas05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import the pandas library, which is essential for working with DataFrames
import pandas as pd

# Create a dictionary named 'dct' to store data
# This dictionary contains three lists: 'name', 'age', and 'roll'
# Each list represents a column of data
dct = {
    'name' : ['tom','nick','krish','jack'], # List of names
    'age' : [20,21,19,18],          # List of ages
    'roll' : [1,2,3,4]              # List of roll numbers
}

# Create a pandas DataFrame named 'df' from the 'dct' dictionary
# A DataFrame is a 2-dimensional labeled data structure with columns of potentially different types.
# It's similar to a spreadsheet or SQL table, or a dictionary of Series objects.
df = pd.DataFrame(dct)

# Create another pandas DataFrame named 'df1' using the same 'dct' dictionary
# This creates a separate copy of the DataFrame with the same data
df1 = pd.DataFrame(dct)

# The following lines are commented out as they are alternative ways to print/display DataFrames
# print(df) # This would print the DataFrame to the console
# df        # In a Colab notebook, just typing the DataFrame name on the last line displays it
# df1       # This would display df1 if it were the last line

# Display the 'df' DataFrame in a nicely formatted table in the Colab output
display(df)

# Display the 'df1' DataFrame in a nicely formatted table in the Colab output
display(df1)

    name  age  roll
0    tom   20     1
1   nick   21     2
2  krish   19     3
3   jack   18     4

In [ ]:
# Import the pandas library, which is crucial for data manipulation and analysis.
import pandas as pd

# Read the CSV file 'student_data.csv' into a pandas DataFrame.
# A DataFrame is a tabular data structure with labeled axes (rows and columns),
# similar to a spreadsheet or a database table.
df = pd.read_csv('student_data.csv')

# Display the entire DataFrame 'df' in a formatted table in the output.
# In Google Colab, `display()` is often preferred over `print()` for DataFrames
# as it provides a more interactive and readable output.
display(df)

# Display the last 3 rows of the DataFrame 'df'.
# The `.tail()` method is useful for quickly inspecting the end of your dataset.
# If no number is specified, it defaults to showing the last 5 rows.
df.tail(3)

# Print a concise summary of the DataFrame.
# This includes the index dtype and column dtypes, non-null values, and memory usage.
# It's very useful for a quick check on data types and missing values.
df.info()

# Generate descriptive statistics of the DataFrame's numerical columns.
# This includes count, mean, standard deviation, minimum, maximum, and quartile values.
# It provides a quick overview of the central tendency, dispersion, and shape of the distribution.
df.describe()

# Return a tuple representing the dimensions of the DataFrame (rows, columns).
# This tells you exactly how many rows and columns your dataset has.
df.shape

# Display the names of all columns in the DataFrame.
# This is helpful to see all available features or variables in your dataset.
df.columns

# Display the row index labels of the DataFrame.
# For most DataFrames read from CSV, this will be a `RangeIndex` starting from 0.
df.index

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   study_hours            10000 non-null  int64
 1   attendance             10000 non-null  int64
 2   sleep_hours            10000 non-null  int64
 3   internet_usage         10000 non-null  int64
 4   assignments_completed  10000 non-null  int64
 5   previous_score         10000 non-null  int64
 6   exam_score             10000 non-null  float64
 7   placement_status       10000 non-null  object
dtypes: float64(1), int64(6), object(1)
memory usage: 625.1+ KB

RangeIndex(start=0, stop=10000, step=1)

In [ ]:
df = pd.read_csv('student_data.csv')

df['internet_usage']

df[['study_hours' ,'internet_usage']]

df.iloc[0]

      study_hours  internet_usage
0               7               7
1               4               3
2              11               6
3               8               8
4               5               6
...           ...             ...
9995            2               7
9996            7               9
9997           10               5
9998           10               5
9999            2              11

[10000 rows x 2 columns]

In [22]:
# Pandas DataFrame mein Data ko kaise access karte hain, iloc aur loc ka use karke

# --- Integer-location based indexing (iloc) ---
# 'iloc' ka use rows aur columns ko unki integer position (yaani index number) ke hisab se select karne ke liye hota hai.

# DataFrame ki pehli (first) row ko select aur display karte hain.
# 'iloc[0]' ka matlab hai 'integer index 0 par jo row hai, woh laao'.
# Isse ek pandas Series return hoti hai, jahan index column ke naam hote hain aur values us row ka data.
print("\n--- Pehli Row (iloc[0]) ---")
display(df.iloc[0]) # 'display' function output ko achhe se dikhati hai

# DataFrame ki pehli 5 rows ko select aur display karte hain.
# 'iloc[0:5]' ka matlab hai 'integer index 0 se shuru karke index 5 tak (lekin 5 ko shamil nahi karna) saari rows laao'.
# Isse ek naya DataFrame return hota hai jismein yeh rows hoti hain.
print("\n--- Pehli 5 Rows (iloc[0:5]) ---")
display(df.iloc[0:5])

# --- Label-based indexing (loc) ---
# 'loc' ka use rows aur columns ko unke labels (jaise column names, ya custom row labels) se select karne ke liye hota hai.
# Yeh data ko filter karne ke liye boolean conditions (True/False conditions) ko bhi support karta hai.

# Un sabhi rows ko select aur display karte hain jahan 'study_hours' column ki value 11 hai.
# Sabse pehle, `df['study_hours']==11` ek boolean Series banata hai (har row ke liye True ya False).
# Phir, `df.loc[...]` is boolean Series ka use karke sirf un rows ko select karta hai jahan condition True hai.
print("\n--- Rows jahan 'study_hours' 11 hai (loc with boolean indexing) ---")
display(df.loc[df['study_hours']==11])

# Un rows ko select aur display karte hain jahan 'study_hours' 11 hai, lekin sirf 'study_hours' aur 'sleep_hours' columns ko hi dikhate hain.
# Yahan, hum rows ko filter karne ke liye boolean indexing (`df['study_hours']==11`) ko columns ko select karne ke liye label-based indexing (`['study_hours','sleep_hours']`) ke saath combine kar rahe hain.
# `['study_hours','sleep_hours']` specifies karta hai ki filtered rows ke liye kaun se columns dikhane hain.
print("\n--- 'study_hours' aur 'sleep_hours' un rows ke liye jahan 'study_hours' 11 hai ---")
display(df.loc[df['study_hours']==11 , ['study_hours','sleep_hours']])

# Ek aur advanced example:
# Pehle hum 'study_hours' 11 wali rows lete hain aur unse sirf 'study_hours' aur 'sleep_hours' columns nikalte hain.
# Uske baad, `.iloc[4:8]` ka use karke, us chhote data set mein se integer index 4 se 8 (8 shamil nahi) tak ki rows ko select karte hain.
# Yeh dikhata hai ki aap 'loc' aur 'iloc' ko chain bhi kar sakte hain.
print("\n--- Chained loc aur iloc: study_hours=11 wali rows se kuch specific columns, aur phir unmein se kuch specific rows ---")
display(df.loc[df['study_hours']==11 , ['study_hours','sleep_hours']].iloc[4:8])

# Ab hum ek naya DataFrame 'df2' banate hain.
# Is 'df2' mein sirf woh rows hongi jahan 'study_hours' ki value 11 hai.
df2 = df.loc[df['study_hours']==11]
print("\n--- Naya DataFrame 'df2' (jahan study_hours = 11) ---")
display(df2)

# 'df2' DataFrame mein se sirf 'study_hours' aur 'sleep_hours' columns ko select karke dikhate hain.
# Yeh double square brackets `[['col1', 'col2']]` ka use karke multiple columns select karne ka tareeka hai.
print("\n--- 'df2' mein se sirf 'study_hours' aur 'sleep_hours' columns ---")
display(df2[['study_hours' , 'sleep_hours']])

# 'df2' DataFrame mein se integer index 4 se 8 (8 shamil nahi) tak ki rows ko select karte hain.
# Kyunki 'df2' ab chhota hai, iski 'iloc' indexing original 'df' se alag hogi.
print("\n--- 'df2' mein se integer index 4 se 8 tak ki rows ---")
display(df2.iloc[4:8])

--- First Row (iloc[0]) ---

--- First 5 Rows (iloc[0:5]) ---

--- Rows where 'study_hours' is 11 (loc with boolean indexing) ---

--- 'study_hours' and 'sleep_hours' for rows where 'study_hours' is 11 ---

      study_hours  sleep_hours
2              11            7
9              11            4
10             11            8
29             11            9
30             11            5
...           ...          ...
9969           11            8
9971           11            9
9978           11            8
9979           11            9
9988           11            6

[868 rows x 2 columns]

In [27]:
# Q.1
import pandas as pd

df = pd.read_csv('student_data.csv')
df.loc[df['assignments_completed']==8].iloc[1]

study_hours                   5
attendance                   52
sleep_hours                   8
internet_usage                6
assignments_completed         8
previous_score               40
exam_score                78.82
placement_status         Placed
Name: 4, dtype: object

In [30]:
df = pd.read_csv('student_data.csv')

# Yeh code un rows ko filter karta hai jahan 'assignments_completed' 3 se zyada hain
# aur filtered DataFrame ko display karta hai.
# Lekin yeh change 'df' mein save nahi karta hai.
display(df[df['assignments_completed']>3])


# --- Column ko rename karna (Corrected Code) ---

# Yahan `columns` keyword ka use hoga, `colume` ka nahi.
# Aur column ka sahi naam `'assignments_completed'` hai.
# `inplace=True` ka use karne par, aapko DataFrame ko dobara assign karne ki zarurat nahi hoti hai.
# Agar aap naya DataFrame banana chahte hain, toh `inplace=True` use na karein aur result ko ek naye variable mein assign karein.

# Pehla tareeka (recommended): `inplace=False` by default hota hai, isliye hum naye renamed DataFrame ko `df` mein assign kar rahe hain.
df = df.rename(columns = { 'assignments_completed':'assign_completed'})

# Dusra tareeka: `inplace=True` ka use karke DataFrame ko directly modify karna.
# Is case mein, assignment (`df = ...`) ki zarurat nahi hai, kyunki function khud `df` ko badal deta hai.
# Lekin, `df.rename(...)` None return karega, aur agar aap use assign karoge toh `df` None ho jayega.
# Isliye, correct way hai:
# df.rename(columns = { 'assignments_completed':'assign_completed'}, inplace=True)

# Ab modified 'df' ko display karein taaki changes dikhein
print("\n--- DataFrame after renaming column ---")
display(df.head())

# df.drop(1) # Yeh line ek row ko drop karne ke liye thi, abhi ise comment rakhte hain

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
5,7,40,9,10,0,60,72.33,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [34]:
import pandas as pd

df = pd.read_csv('student_data.csv')

# Remove rows or columns
df.drop(1)

# Remove missing values
df.dropna()

# Sort values by column
df.sort_values()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
5,7,40,9,10,0,60,72.33,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed